path: /Users/parimi/Documents/TAMU/RA_Work/data  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')
test: images/test #test images (relative to 'path')

# Classes
names:
  # 0: 'person'
  # 1: 'bicycle'
  # 2: 'car'
  # 3: 'motorcycle'
  # 4: 'bus'
  # 5: 'train'
  # 6: 'truck'
  # 7: 'rider'
  0: 'car'